# pledge.toml
[database]
url = "postgres://postgres:password@localhost:5432/pledge"
host = "localhost"
port = "5432"
user = "postgres"
password = "password"
database = "pledge"

[cache]
global_ttl = 30
max_size_mib = 10

[server]
port = 3000
#https_port = 3001
#tls_cert_path = "certs/test-cert.pem"
#tls_key_path = "certs/test-key.pem"

[[queries]]
name = "get_user"
sql = "SELECT id, name FROM users WHERE id = $1"
ttl = 300

[[queries]]
name = "get_users_where_email_like_x_or_y"
sql = "SELECT * FROM users where email like $1 or email like $2"
ttl = 300

[[queries]]
name = "get_posts"
sql = "SELECT * FROM posts WHERE user_id = $1"
ttl = 600

[[queries]]
name = "insert_user"
sql = "INSERT INTO users (name, email) VALUES ($1, $2) RETURNING id"

[[queries]]
name = "get_users_with_posts"
sql = "SELECT u.id, u.name, p.id AS post_id, p.title FROM users u JOIN posts p ON u.id = p.user_id"

[[queries]]
name = "cross_join_users"
sql = "SELECT u1.email, u2.email, u1.id + u2.id as combined_id FROM users u1 CROSS JOIN users u2 WHERE u1.id < $1 AND u2.id < $2"

[[queries]]
name = "search_users_by_content_limit_20"
sql = "SELECT u.email, COUNT(*) as match_count, MAX(p.created_at) as latest_match FROM users u JOIN posts p ON u.id = p.user_id WHERE p.content ILIKE $1 OR p.content ILIKE $2 OR p.title ILIKE $3 GROUP BY u.email ORDER BY match_count DESC LIMIT 20"
ttl = 30

[[queries]]
name = "search_users_by_content_limit_100"
sql = "SELECT u.email, COUNT(*) as match_count, MAX(p.created_at) as latest_match FROM users u JOIN posts p ON u.id = p.user_id WHERE p.content ILIKE $1 OR p.content ILIKE $2 OR p.title ILIKE $3 GROUP BY u.email ORDER BY match_count DESC LIMIT 100"
ttl = 30

[[queries]]
name = "search_users_by_content_limit_1000"
sql = "SELECT u.email, COUNT(*) as match_count, MAX(p.created_at) as latest_match FROM users u JOIN posts p ON u.id = p.user_id WHERE p.content ILIKE $1 OR p.content ILIKE $2 OR p.title ILIKE $3 GROUP BY u.email ORDER BY match_count DESC LIMIT 1000"
ttl = 600

[[queries]]
name = "search_users_by_content_limit_100_no_param"
sql = "SELECT u.email, COUNT(*) as match_count, MAX(p.created_at) as latest_match FROM users u JOIN posts p ON u.id = p.user_id WHERE p.content ILIKE '%lorem%' OR p.content ILIKE '%ipsum%' OR p.title ILIKE '%Post%' GROUP BY u.email ORDER BY match_count DESC LIMIT 100;"

[[queries]]
name = "search_users_by_content_limit_99_no_param"
sql = "SELECT u.email, COUNT(*) as match_count, MAX(p.created_at) as latest_match FROM users u JOIN posts p ON u.id = p.user_id WHERE p.content ILIKE '%lorem%' OR p.content ILIKE '%ipsum%' OR p.title ILIKE '%Post%' GROUP BY u.email ORDER BY match_count DESC LIMIT 99;"
ttl = 15

[[queries]]
name = "search_users_by_content_limit_98_no_param"
sql = "SELECT u.email, COUNT(*) as match_count, MAX(p.created_at) as latest_match FROM users u JOIN posts p ON u.id = p.user_id WHERE p.content ILIKE '%lorem%' OR p.content ILIKE '%ipsum%' OR p.title ILIKE '%Post%' GROUP BY u.email ORDER BY match_count DESC LIMIT 98;"
ttl = 15
